### ISSUE TITLE
A language key is displayed in wrong place

### ISSUE THREAD

**Issue by Galixte** [phpbbmodders/phpbb-3.1-ext-usermerge#5]
Hi @tumba25 & @RMcGirr83,

In ACP => “USERS AND GROUPS” tab => “Users” => “Manage users”, if i enter an email like test@test.com in “Enter username” field an error message is displayed: ```A specified user for merging could not be located within the database.``` instead of ```The requested user does not exist.```.

This language key comes from this extension: https://github.com/phpbbmodders/phpbb-3.1-ext-usermerge/blob/master/language/en/info_acp_usermerge.php#L37.

**Comment by Galixte** [comment]
Hi @bonelifer,

could you take a look, please ?

**Comment by bonelifer** [comment]
@RMcGirr83 Could you look at it please.

**Comment by RMcGirr83** [comment]
@bonelifer Made a pull request

**Comment by bonelifer** [comment]
@RMcGirr83 #6 Merged

**Comment by Galixte** [comment]
Thanks to you, it"s fixed.
